version: '3.8'
services:
  pgadmin:
    container_name: rds_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
  postgres:
    container_name: rds_postgres
    image: 'postgres:13'
    env_file:
      - .env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - '5434:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './init-db.sh:/docker-entrypoint-initdb.d/01-init-db.sh'
    networks:
      - rds_network
    restart: unless-stopped
  api:
    container_name: rds_api
    build:
      context: .
    ports:
      - 8000:8080
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - '.:/usr/src/rds'
    networks:
      - rds_network
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
volumes:
  pgadmin_data: {}
  postgres_data: {}
  mongo_data: {}
networks:
  rds_network:
    driver: bridge
